# Generated by Django 3.1.3 on 2020-11-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areanames',
            name='region',
        ),
    ]
