# Generated by Django 3.1.3 on 2020-11-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=90)),
            ],
        ),
    ]
