# Generated by Django 3.1.3 on 2020-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='name',
            field=models.TextField(max_length=15),
        ),
    ]
